name: msvc-dev-cmd (release)

on:
  push:
    branches:
      - release/*
    paths:
      - .github/workflows/release.yml
  schedule:
    - cron: '0 0 * * *'

jobs:
  test:
    name: release
    runs-on: windows-latest
    strategy:
      fail-fast: false
    steps:
      - name: Setup Developer Command Prompt
        uses: qRoC/msvc-dev-cmd@v1
      - name: Check out source code
        uses: actions/checkout@v1
      - name: Compile and run some C code
        shell: cmd
        run: |
          cl.exe hello.c
          hello.exe
  audit:
    name: npm audit
    runs-on: windows-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v1
      - run: npm audit --audit-level=moderate
